#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.7.3
# from Racc grammar file "mork.y".
#

require 'racc/parser.rb'



module Mork
  class Parser < Racc::Parser

module_eval(<<'...end mork.y/module_eval...', 'mork.y', 59)

require "mork/lexer"
require "mork/raw"
require "mork/raw/alias"
require "mork/raw/cell"
require "mork/raw/dictionary"
require "mork/raw/group"
require "mork/raw/meta_alias"
require "mork/raw/meta_table"
require "mork/raw/row"
require "mork/raw/table"

attr_reader :lexer

def parse(str)
  @lexer = Mork::Lexer.new
  lexer.scan_setup(str)
  do_parse
end

def next_token
  lexer.next_token
end

...end mork.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    22,    22,    22,    22,     9,     9,     2,    11,    60,    61,
     3,    10,    10,    11,    11,    35,    36,    37,    13,    12,
    12,    24,    24,    24,    24,    26,    26,    26,    26,     9,
     9,    31,     9,     9,     9,    38,    10,    10,    11,    11,
    10,    11,    11,    11,    12,    12,     9,    12,    12,    12,
     9,    60,    61,    42,    11,    11,    60,    61,    11,    11,
    24,    12,    35,    36,    37,    12,    35,    36,    37,    11,
    44,    26,    11,    46,    47,    53,    54,    35,    36,    37,
    35,    36,    37,    62,    63,    64,    65,    53,    67,    68,
    71,    72,    73,    74 ]

racc_action_check = [
     9,    19,    20,    21,     2,     5,     0,    12,    37,    37,
     1,     2,     5,     2,     5,    12,    12,    12,     3,     2,
     5,     9,    19,    20,    21,     9,    19,    20,    21,     6,
     7,    11,    10,     8,    28,    18,     6,     7,     6,     7,
     8,    10,     8,    28,     6,     7,    29,    10,     8,    28,
    30,    60,    60,    22,    33,    29,    61,    61,    34,    30,
    23,    29,    33,    33,    33,    30,    34,    34,    34,    35,
    24,    25,    36,    26,    27,    31,    32,    35,    35,    35,
    36,    36,    36,    42,    44,    46,    51,    52,    53,    59,
    62,    63,    67,    71 ]

racc_action_pointer = [
     4,    10,     1,    18,   nil,     2,    26,    27,    30,    -5,
    29,    18,    -5,   nil,   nil,   nil,   nil,   nil,    31,    -4,
    -3,    -2,    47,    34,    43,    41,    42,    63,    31,    43,
    47,    60,    57,    42,    46,    57,    60,   -16,   nil,   nil,
   nil,   nil,    76,   nil,    56,   nil,    53,   nil,   nil,   nil,
   nil,    72,    72,    72,   nil,   nil,   nil,   nil,   nil,    66,
    27,    32,    82,    62,   nil,   nil,   nil,    75,   nil,   nil,
   nil,    84,   nil,   nil,   nil ]

racc_action_default = [
   -38,   -38,    -2,   -38,    -1,    -2,    -2,    -2,    -2,    -8,
   -14,   -38,   -23,    75,    -3,    -4,    -5,    -6,   -38,    -8,
    -8,    -8,   -38,   -32,   -38,   -35,   -38,   -38,   -14,   -14,
   -14,   -19,   -38,   -23,   -23,   -23,   -23,   -29,    -7,    -9,
   -10,   -11,   -38,   -33,   -38,   -36,   -38,   -13,   -15,   -16,
   -17,   -38,   -19,   -38,   -22,   -24,   -25,   -26,   -27,   -38,
   -29,   -29,   -38,   -38,   -37,   -18,   -20,   -38,   -28,   -30,
   -31,   -38,   -34,   -21,   -12 ]

racc_goto_table = [
    29,    51,    34,     1,    45,    43,    32,     4,    59,   nil,
    14,    15,    16,    17,   nil,    28,   nil,   nil,    29,    29,
    29,    30,    66,    34,    34,    34,    34,    55,    56,    57,
    58,    69,    70,    28,    28,    28,    27,    18,   nil,    30,
    30,    30,   nil,   nil,   nil,   nil,   nil,    39,    40,    41,
   nil,   nil,   nil,   nil,    48,    49,    50 ]

racc_goto_check = [
     5,    12,     5,     1,     9,    10,    14,     2,    16,   nil,
     2,     2,     2,     2,   nil,     3,   nil,   nil,     5,     5,
     5,     6,    12,     5,     5,     5,     5,    14,    14,    14,
    14,    16,    16,     3,     3,     3,    11,     7,   nil,     6,
     6,     6,   nil,   nil,   nil,   nil,   nil,     7,     7,     7,
   nil,   nil,   nil,   nil,    11,    11,    11 ]

racc_goto_pointer = [
   nil,     3,     5,     5,   nil,   -10,    11,    28,   nil,   -21,
   -18,    26,   -30,   nil,    -6,   nil,   -29,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     5,     6,     7,     8,   nil,    19,    20,
    21,   nil,   nil,    52,   nil,    33,   nil,    23,    25 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 34, :_reduce_1,
  0, 35, :_reduce_2,
  2, 35, :_reduce_3,
  2, 35, :_reduce_4,
  2, 35, :_reduce_5,
  2, 35, :_reduce_6,
  3, 36, :_reduce_7,
  0, 40, :_reduce_8,
  2, 40, :_reduce_9,
  2, 40, :_reduce_10,
  2, 40, :_reduce_11,
  5, 41, :_reduce_12,
  3, 37, :_reduce_13,
  0, 44, :_reduce_14,
  2, 44, :_reduce_15,
  2, 44, :_reduce_16,
  2, 44, :_reduce_17,
  4, 38, :_reduce_18,
  0, 45, :_reduce_none,
  2, 45, :_reduce_20,
  3, 46, :_reduce_21,
  3, 39, :_reduce_22,
  0, 47, :_reduce_23,
  2, 47, :_reduce_24,
  2, 47, :_reduce_25,
  2, 47, :_reduce_26,
  2, 47, :_reduce_27,
  3, 48, :_reduce_28,
  0, 49, :_reduce_none,
  2, 49, :_reduce_none,
  2, 49, :_reduce_none,
  0, 43, :_reduce_none,
  2, 43, :_reduce_33,
  4, 50, :_reduce_34,
  0, 42, :_reduce_none,
  2, 42, :_reduce_none,
  3, 51, :_reduce_none ]

racc_reduce_n = 38

racc_shift_n = 75

racc_token_table = {
  false => 0,
  :error => 1,
  :magic => 2,
  :dictionary_in => 3,
  :dictionary_out => 4,
  :meta_in => 5,
  :meta_alias_in => 6,
  :meta_alias => 7,
  :meta_alias_out => 8,
  :meta_out => 9,
  :group_in => 10,
  :group_out => 11,
  :row_in => 12,
  :row_mid => 13,
  :row_out => 14,
  :cell_in => 15,
  :cell_value => 16,
  :cell_out => 17,
  :table_in => 18,
  :table_out => 19,
  :row_delete => 20,
  :table_row_ref => 21,
  :meta_table_in => 22,
  :meta_table_out => 23,
  :meta_table_cell => 24,
  :meta_table_row_ref => 25,
  :alias_in => 26,
  :alias_key => 27,
  :alias_value => 28,
  :alias_out => 29,
  :comment_in => 30,
  :comment_text => 31,
  :comment_out => 32 }

racc_nt_base = 33

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "magic",
  "dictionary_in",
  "dictionary_out",
  "meta_in",
  "meta_alias_in",
  "meta_alias",
  "meta_alias_out",
  "meta_out",
  "group_in",
  "group_out",
  "row_in",
  "row_mid",
  "row_out",
  "cell_in",
  "cell_value",
  "cell_out",
  "table_in",
  "table_out",
  "row_delete",
  "table_row_ref",
  "meta_table_in",
  "meta_table_out",
  "meta_table_cell",
  "meta_table_row_ref",
  "alias_in",
  "alias_key",
  "alias_value",
  "alias_out",
  "comment_in",
  "comment_text",
  "comment_out",
  "$start",
  "start",
  "top_level",
  "dictionary",
  "group",
  "row",
  "table",
  "dictionary_contents",
  "meta",
  "comments",
  "aliases",
  "group_content",
  "cells",
  "cell",
  "table_content",
  "meta_table",
  "meta_table_content",
  "alias",
  "comment" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'mork.y', 8)
  def _reduce_1(val, _values, result)
     result = Mork::Raw.new(values: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 9)
  def _reduce_2(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 10)
  def _reduce_3(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 11)
  def _reduce_4(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 12)
  def _reduce_5(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 13)
  def _reduce_6(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 15)
  def _reduce_7(val, _values, result)
     result = Mork::Raw::Dictionary.new(values: val[1].flatten.compact)
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 16)
  def _reduce_8(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 17)
  def _reduce_9(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 19)
  def _reduce_10(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 20)
  def _reduce_11(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 21)
  def _reduce_12(val, _values, result)
     result = Mork::Raw::MetaAlias.new(raw: val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 23)
  def _reduce_13(val, _values, result)
     result = Mork::Raw::Group.new(values: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 24)
  def _reduce_14(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 25)
  def _reduce_15(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 26)
  def _reduce_16(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 27)
  def _reduce_17(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 29)
  def _reduce_18(val, _values, result)
     result = Mork::Raw::Row.new(raw_id: val[1], cells: val[2])
    result
  end
.,.,

# reduce 19 omitted

module_eval(<<'.,.,', 'mork.y', 31)
  def _reduce_20(val, _values, result)
     result = val.flatten.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 32)
  def _reduce_21(val, _values, result)
     result = Mork::Raw::Cell.new(raw: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 34)
  def _reduce_22(val, _values, result)
     result = Mork::Raw::Table.new(raw_id: val[0], values: val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 35)
  def _reduce_23(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 36)
  def _reduce_24(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 37)
  def _reduce_25(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 38)
  def _reduce_26(val, _values, result)
     result = [Mork::Raw::Row.new(raw_id: val[0], cells: [])] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 39)
  def _reduce_27(val, _values, result)
     result = [val[0]] + val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 40)
  def _reduce_28(val, _values, result)
     result = Mork::Raw::MetaTable.new(raw: val[1])
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

module_eval(<<'.,.,', 'mork.y', 46)
  def _reduce_33(val, _values, result)
     result = val.flatten.compact
    result
  end
.,.,

module_eval(<<'.,.,', 'mork.y', 47)
  def _reduce_34(val, _values, result)
     result = Mork::Raw::Alias.new(key: val[1], value: val[2])
    result
  end
.,.,

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Mork


#
